#!/bin/bash

#Nano
for i in {1..2};
do 
    list="${i}x32"
    for v in {0..7};
    do
        args=`echo "64 + 8 + 2 + 1" | bc` #64 nano + 2 reps
        echo "command: do_all_agg $i $args $v"
        ./do_all_agg "$i" $args $v;
        echo "command: do_all_agg "$list" $args $v"
        ./do_all_agg "$list" $args $v;

        args=`echo "64 + 16 + 8 + 1" | bc` #64 nano + 16 count
        echo "command: do_all_agg "$i" $args $v"
        ./do_all_agg "$i" $args $v;
        echo "command: do_all_agg "$list" $args $v"
        ./do_all_agg "$list" $args $v;

        args=`echo "64 + 32 + 2" | bc` #64 nano + 32 improved + 2 reps
        echo "command: do_all_agg "$i" $args $v"
        ./do_all_agg "$i" $args $v;
        echo "command: do_all_agg "$list" $args $v"
        ./do_all_agg "$list" $args $v;
    done
done

#Nano
for i in {3..4};
do 
    list="${i}x32"
    for v in {0..7};
    do
        args=`echo "8 + 2 + 1" | bc` #2 reps
        echo "command: do_all_agg $i $args $v"
        ./do_all_agg "$i" $args $v;
        echo "command: do_all_agg "$list" $args $v"
        ./do_all_agg "$list" $args $v;

        args=`echo "16 + 8 + 1" | bc` #16 count
        echo "command: do_all_agg "$i" $args $v"
        ./do_all_agg "$i" $args $v;
        echo "command: do_all_agg "$list" $args $v"
        ./do_all_agg "$list" $args $v;

        args=`echo "32 + 2" | bc` #32 improved + 2 reps
        echo "command: do_all_agg "$i" $args $v"
        ./do_all_agg "$i" $args $v;
        echo "command: do_all_agg "$list" $args $v"
        ./do_all_agg "$list" $args $v;
    done
done
