#!/bin/bash

n="525"

if [[ $# -gt 0 ]]
then
    n=$1
fi

echo "Running on length $n"

v="14"

if [[ $# -gt 1 ]]
then
    v=$2
    echo "Running on variation $v"
fi

for i in {5..7};
do
    LIST_PATH="./lists/list"$n"_"$i
    RUN_PATH="./runs/run"$n"/"
    RUN_FILE="run_on_list"$n"_"$i".txt"
    [ -d $RUN_PATH ] || mkdir -p $RUN_PATH
    echo "Running variation $i"
    ./cmake-build-debug/CS361A2 $v < $LIST_PATH &>> $RUN_PATH$RUN_FILE
done

echo "Done..."

./do_all 5 24

./do_all 525 8

./do_all 55 8

